### ISSUE TITLE
每秒高达1300万中文简体字准确分词是在什么环境下测试得到的？

### ISSUE THREAD

**Issue by wangyjx** [yaoguangluo/Nero_Parser#12]
请问能否分享一下 测试结果是在什么软硬件配置下实现的

**Comment by yaoguangluo** [comment]
win7， 64位， 16g ram，intel i5-7500 测试得到的

**Comment by yaoguangluo** [comment]
软件用的是eclipse， 并启用了sonar认证写法的方式，如果去掉sonar，中文简体分词可达 1700万+

**Comment by wangyjx** [comment]
Thanks
